version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nebula
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    env_file:
      - backend/.env.example
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  frontend:
    build: ./frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend
volumes:
  db_data:
